# Generated by Django 5.0.6 on 2024-05-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontbackdev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
